[2024-05-30T08:37:49.232+0000] {processor.py:153} INFO - Started process (PID=350) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:37:49.234+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:37:49.235+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:37:49.235+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:37:49.843+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:37:49.842+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:37:49.844+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:37:49.890+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.664 seconds
[2024-05-30T08:38:20.502+0000] {processor.py:153} INFO - Started process (PID=361) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:20.505+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:38:20.507+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:38:20.507+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:20.865+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:38:20.864+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:38:20.865+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:20.876+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.382 seconds
[2024-05-30T08:38:36.791+0000] {processor.py:153} INFO - Started process (PID=367) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:36.793+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:38:36.794+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:38:36.794+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:37.180+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:38:37.179+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:38:37.180+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:38:37.194+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.412 seconds
[2024-05-30T08:39:07.315+0000] {processor.py:153} INFO - Started process (PID=378) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:07.320+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:39:07.323+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:39:07.323+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:07.772+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:39:07.771+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:39:07.772+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:07.786+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.488 seconds
[2024-05-30T08:39:38.515+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:38.518+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:39:38.519+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:39:38.519+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:38.921+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:39:38.920+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:39:38.922+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:39:38.937+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.432 seconds
[2024-05-30T08:40:09.768+0000] {processor.py:153} INFO - Started process (PID=400) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:09.770+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:40:09.771+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:40:09.771+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:10.144+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:40:10.143+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:40:10.144+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:10.157+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.398 seconds
[2024-05-30T08:40:41.026+0000] {processor.py:153} INFO - Started process (PID=411) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:41.029+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:40:41.030+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:40:41.030+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:41.370+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:40:41.369+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:40:41.370+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:40:41.384+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.366 seconds
[2024-05-30T08:41:12.274+0000] {processor.py:153} INFO - Started process (PID=422) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:12.276+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:41:12.277+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:41:12.277+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:12.642+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:41:12.641+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:41:12.642+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:12.655+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.388 seconds
[2024-05-30T08:41:43.491+0000] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:43.493+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:41:43.497+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:41:43.497+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:43.857+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:41:43.856+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:41:43.858+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:41:43.913+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.433 seconds
[2024-05-30T08:42:14.760+0000] {processor.py:153} INFO - Started process (PID=444) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:14.762+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:42:14.763+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:42:14.763+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:15.148+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:42:15.147+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:42:15.148+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:15.174+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.432 seconds
[2024-05-30T08:42:45.399+0000] {processor.py:153} INFO - Started process (PID=455) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:45.401+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:42:45.402+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:42:45.402+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:45.729+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:42:45.728+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:42:45.729+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:42:45.777+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.383 seconds
[2024-05-30T08:43:15.810+0000] {processor.py:153} INFO - Started process (PID=471) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:15.810+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:43:15.811+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:43:15.811+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:15.975+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:43:15.975+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:43:15.976+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:15.987+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.178 seconds
[2024-05-30T08:43:46.040+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:46.043+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:43:46.044+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:43:46.044+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:46.381+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:43:46.380+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:43:46.381+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:43:46.391+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.359 seconds
[2024-05-30T08:44:16.410+0000] {processor.py:153} INFO - Started process (PID=493) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:16.411+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:44:16.411+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:44:16.411+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:16.576+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:44:16.575+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:44:16.576+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:16.584+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.175 seconds
[2024-05-30T08:44:46.707+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:46.707+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:44:46.707+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:44:46.707+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:47.006+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:44:47.005+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:44:47.006+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:44:47.015+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.310 seconds
[2024-05-30T08:45:17.955+0000] {processor.py:153} INFO - Started process (PID=515) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:17.956+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:45:17.957+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:45:17.957+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:18.158+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:45:18.157+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:45:18.159+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:18.166+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.217 seconds
[2024-05-30T08:45:48.267+0000] {processor.py:153} INFO - Started process (PID=526) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:48.269+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:45:48.270+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:45:48.270+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:48.592+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:45:48.591+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:45:48.592+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:45:48.600+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.339 seconds
[2024-05-30T08:46:18.645+0000] {processor.py:153} INFO - Started process (PID=537) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:18.646+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:46:18.647+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:46:18.647+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:18.980+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:46:18.979+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:46:18.980+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:18.990+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.350 seconds
[2024-05-30T08:46:49.865+0000] {processor.py:153} INFO - Started process (PID=548) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:49.866+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:46:49.867+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:46:49.867+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:50.283+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:46:50.282+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:46:50.284+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:46:50.296+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.446 seconds
[2024-05-30T08:47:20.360+0000] {processor.py:153} INFO - Started process (PID=559) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:20.363+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:47:20.364+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:47:20.364+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:20.732+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:47:20.731+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:47:20.732+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:20.741+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.389 seconds
[2024-05-30T08:47:51.572+0000] {processor.py:153} INFO - Started process (PID=570) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:51.574+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:47:51.575+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:47:51.575+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:51.868+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:47:51.867+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:47:51.868+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:47:51.881+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.320 seconds
[2024-05-30T08:48:22.065+0000] {processor.py:153} INFO - Started process (PID=581) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:22.067+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:48:22.068+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:48:22.068+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:22.393+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:48:22.392+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:48:22.394+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:22.403+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.343 seconds
[2024-05-30T08:48:53.347+0000] {processor.py:153} INFO - Started process (PID=592) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:53.349+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:48:53.350+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:48:53.350+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:53.803+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:48:53.802+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:48:53.804+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:48:53.816+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.481 seconds
[2024-05-30T08:49:24.720+0000] {processor.py:153} INFO - Started process (PID=603) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:24.722+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:49:24.723+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:49:24.723+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:25.060+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:49:25.059+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:49:25.061+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:25.073+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.361 seconds
[2024-05-30T08:49:55.141+0000] {processor.py:153} INFO - Started process (PID=614) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:55.144+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:49:55.146+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:49:55.146+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:55.519+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:49:55.517+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:49:55.519+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:49:55.533+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.399 seconds
[2024-05-30T08:50:26.420+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:26.422+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:50:26.423+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:50:26.423+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:26.806+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:50:26.806+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:50:26.807+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:26.819+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.404 seconds
[2024-05-30T08:50:57.788+0000] {processor.py:153} INFO - Started process (PID=636) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:57.790+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:50:57.792+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:50:57.791+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:58.110+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:50:58.109+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:50:58.110+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:50:58.120+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.339 seconds
[2024-05-30T08:51:28.165+0000] {processor.py:153} INFO - Started process (PID=647) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:28.167+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:51:28.168+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:51:28.168+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:28.560+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:51:28.559+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:51:28.560+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:28.573+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.413 seconds
[2024-05-30T08:51:59.362+0000] {processor.py:153} INFO - Started process (PID=658) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:59.365+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:51:59.366+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:51:59.366+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:59.725+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:51:59.724+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:51:59.726+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:51:59.740+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.384 seconds
[2024-05-30T08:52:29.893+0000] {processor.py:153} INFO - Started process (PID=669) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:52:29.895+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:52:29.897+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:52:29.896+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:52:30.273+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:52:30.272+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:52:30.273+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:52:30.285+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.401 seconds
[2024-05-30T08:53:01.179+0000] {processor.py:153} INFO - Started process (PID=680) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:01.181+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:53:01.182+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:53:01.182+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:01.543+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:53:01.542+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:53:01.543+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:01.556+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.383 seconds
[2024-05-30T08:53:31.614+0000] {processor.py:153} INFO - Started process (PID=691) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:31.617+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:53:31.618+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:53:31.618+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:31.996+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:53:31.995+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:53:31.996+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:53:32.008+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.400 seconds
[2024-05-30T08:54:02.837+0000] {processor.py:153} INFO - Started process (PID=702) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:02.839+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:54:02.840+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:54:02.840+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:03.192+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:54:03.191+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:54:03.193+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:03.205+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.370 seconds
[2024-05-30T08:54:33.281+0000] {processor.py:153} INFO - Started process (PID=713) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:33.283+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:54:33.284+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:54:33.284+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:33.689+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:54:33.688+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:54:33.689+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:54:33.711+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.437 seconds
[2024-05-30T08:55:04.524+0000] {processor.py:153} INFO - Started process (PID=724) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:04.526+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:55:04.527+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:55:04.527+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:04.927+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:55:04.926+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:55:04.927+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:04.939+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.422 seconds
[2024-05-30T08:55:35.867+0000] {processor.py:153} INFO - Started process (PID=735) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:35.869+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:55:35.870+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:55:35.870+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:36.268+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:55:36.267+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:55:36.268+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:55:36.281+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.421 seconds
[2024-05-30T08:56:07.180+0000] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:07.183+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:56:07.185+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:56:07.184+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:07.550+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:56:07.549+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:56:07.550+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:07.561+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.390 seconds
[2024-05-30T08:56:38.487+0000] {processor.py:153} INFO - Started process (PID=757) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:38.490+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:56:38.491+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:56:38.491+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:38.898+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:56:38.897+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:56:38.899+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:56:38.910+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.431 seconds
[2024-05-30T08:57:09.789+0000] {processor.py:153} INFO - Started process (PID=768) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:09.791+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:57:09.791+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:57:09.791+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:10.139+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:57:10.138+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:57:10.140+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:10.152+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.367 seconds
[2024-05-30T08:57:41.136+0000] {processor.py:153} INFO - Started process (PID=779) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:41.138+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:57:41.139+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:57:41.139+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:41.567+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:57:41.566+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:57:41.567+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:57:41.589+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.464 seconds
[2024-05-30T08:58:12.538+0000] {processor.py:153} INFO - Started process (PID=790) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:12.540+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:58:12.542+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:58:12.542+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:12.931+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:58:12.930+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:58:12.931+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:12.948+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.416 seconds
[2024-05-30T08:58:43.796+0000] {processor.py:153} INFO - Started process (PID=801) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:43.797+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:58:43.799+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:58:43.799+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:44.157+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:58:44.156+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:58:44.157+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:58:44.170+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.379 seconds
[2024-05-30T08:59:15.086+0000] {processor.py:153} INFO - Started process (PID=812) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:15.089+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:59:15.089+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:59:15.089+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:15.471+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:59:15.470+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:59:15.472+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:15.484+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.402 seconds
[2024-05-30T08:59:46.395+0000] {processor.py:153} INFO - Started process (PID=823) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:46.399+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T08:59:46.399+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:59:46.399+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:46.769+0000] {logging_mixin.py:115} INFO - [2024-05-30T08:59:46.768+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T08:59:46.769+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T08:59:46.782+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.394 seconds
[2024-05-30T09:00:17.732+0000] {processor.py:153} INFO - Started process (PID=834) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:17.736+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:00:17.737+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:00:17.737+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:18.119+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:00:18.118+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:00:18.119+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:18.147+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.421 seconds
[2024-05-30T09:00:49.012+0000] {processor.py:153} INFO - Started process (PID=845) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:49.016+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:00:49.017+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:00:49.017+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:49.346+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:00:49.345+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:00:49.346+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:00:49.358+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.353 seconds
[2024-05-30T09:01:20.223+0000] {processor.py:153} INFO - Started process (PID=856) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:20.227+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:01:20.228+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:01:20.228+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:20.584+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:01:20.583+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:01:20.584+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:20.598+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.381 seconds
[2024-05-30T09:01:51.406+0000] {processor.py:153} INFO - Started process (PID=867) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:51.408+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:01:51.408+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:01:51.408+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:51.762+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:01:51.761+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:01:51.763+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:01:51.776+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.374 seconds
[2024-05-30T09:02:22.682+0000] {processor.py:153} INFO - Started process (PID=878) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:22.685+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:02:22.686+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:02:22.686+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:23.127+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:02:23.126+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:02:23.127+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:23.144+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.465 seconds
[2024-05-30T09:02:54.051+0000] {processor.py:153} INFO - Started process (PID=889) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:54.053+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:02:54.054+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:02:54.054+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:54.541+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:02:54.540+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:02:54.542+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:02:54.556+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.509 seconds
[2024-05-30T09:03:25.362+0000] {processor.py:153} INFO - Started process (PID=900) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:25.364+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:03:25.365+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:03:25.365+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:25.734+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:03:25.733+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:03:25.734+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:25.746+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.389 seconds
[2024-05-30T09:03:56.646+0000] {processor.py:153} INFO - Started process (PID=911) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:56.648+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:03:56.649+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:03:56.649+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:57.008+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:03:57.007+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:03:57.008+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:03:57.021+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.382 seconds
[2024-05-30T09:04:27.968+0000] {processor.py:153} INFO - Started process (PID=922) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:27.970+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:04:27.971+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:04:27.971+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:28.363+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:04:28.362+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:04:28.363+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:28.375+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.414 seconds
[2024-05-30T09:04:59.249+0000] {processor.py:153} INFO - Started process (PID=933) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:59.252+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:04:59.253+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:04:59.253+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:59.609+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:04:59.608+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:04:59.609+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:04:59.618+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.375 seconds
[2024-05-30T09:05:29.746+0000] {processor.py:153} INFO - Started process (PID=949) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:05:29.747+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:05:29.747+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:05:29.747+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:05:30.127+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:05:30.127+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:05:30.128+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:05:30.139+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.394 seconds
[2024-05-30T09:06:00.962+0000] {processor.py:153} INFO - Started process (PID=960) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:00.964+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:06:00.965+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:06:00.965+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:01.315+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:06:01.313+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:06:01.315+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:01.330+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.373 seconds
[2024-05-30T09:06:31.395+0000] {processor.py:153} INFO - Started process (PID=971) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:31.398+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:06:31.399+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:06:31.399+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:31.737+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:06:31.736+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:06:31.737+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:06:31.750+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.359 seconds
[2024-05-30T09:07:02.577+0000] {processor.py:153} INFO - Started process (PID=982) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:02.579+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:07:02.580+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:07:02.580+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:02.920+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:07:02.919+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:07:02.920+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:02.929+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.357 seconds
[2024-05-30T09:07:33.064+0000] {processor.py:153} INFO - Started process (PID=993) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:33.069+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:07:33.070+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:07:33.070+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:33.411+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:07:33.410+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:07:33.412+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:07:33.421+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.362 seconds
[2024-05-30T09:08:04.323+0000] {processor.py:153} INFO - Started process (PID=1004) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:04.325+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:08:04.325+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:08:04.325+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:04.664+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:08:04.663+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:08:04.665+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:04.674+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.356 seconds
[2024-05-30T09:08:34.757+0000] {processor.py:153} INFO - Started process (PID=1015) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:34.759+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:08:34.760+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:08:34.760+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:35.120+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:08:35.119+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:08:35.120+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:08:35.132+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.378 seconds
[2024-05-30T09:09:05.973+0000] {processor.py:153} INFO - Started process (PID=1026) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:05.974+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:09:05.975+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:09:05.975+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:06.325+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:09:06.324+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:09:06.325+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:06.336+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.368 seconds
[2024-05-30T09:09:36.501+0000] {processor.py:153} INFO - Started process (PID=1037) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:36.502+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:09:36.503+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:09:36.503+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:36.863+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:09:36.862+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:09:36.863+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:09:36.875+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.381 seconds
[2024-05-30T09:10:07.734+0000] {processor.py:153} INFO - Started process (PID=1048) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:07.737+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:10:07.739+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:10:07.738+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:08.074+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:10:08.073+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:10:08.075+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:08.086+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.358 seconds
[2024-05-30T09:10:38.256+0000] {processor.py:153} INFO - Started process (PID=1059) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:38.259+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:10:38.261+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:10:38.260+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:38.627+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:10:38.626+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:10:38.627+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:10:38.640+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.391 seconds
[2024-05-30T09:11:09.403+0000] {processor.py:153} INFO - Started process (PID=1070) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:09.405+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:11:09.405+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:11:09.405+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:09.723+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:11:09.722+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:11:09.723+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:09.734+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.334 seconds
[2024-05-30T09:11:39.865+0000] {processor.py:153} INFO - Started process (PID=1081) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:39.868+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:11:39.870+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:11:39.870+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:40.206+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:11:40.205+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:11:40.206+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:11:40.224+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.366 seconds
[2024-05-30T09:12:11.060+0000] {processor.py:153} INFO - Started process (PID=1092) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:11.063+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:12:11.064+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:12:11.064+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:11.389+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:12:11.388+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:12:11.389+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:11.400+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.345 seconds
[2024-05-30T09:12:41.613+0000] {processor.py:153} INFO - Started process (PID=1103) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:41.614+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:12:41.615+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:12:41.615+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:41.993+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:12:41.992+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:12:41.994+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:12:42.005+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.397 seconds
[2024-05-30T09:13:12.857+0000] {processor.py:153} INFO - Started process (PID=1114) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:12.860+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:13:12.862+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:13:12.861+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:13.200+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:13:13.199+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:13:13.200+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:13.212+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.361 seconds
[2024-05-30T09:13:43.272+0000] {processor.py:153} INFO - Started process (PID=1125) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:43.274+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:13:43.275+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:13:43.275+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:43.606+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:13:43.605+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:13:43.606+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:13:43.615+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.349 seconds
[2024-05-30T09:14:13.747+0000] {processor.py:153} INFO - Started process (PID=1136) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:13.749+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:14:13.750+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:14:13.750+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:14.081+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:14:14.080+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:14:14.081+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:14.091+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.350 seconds
[2024-05-30T09:14:44.999+0000] {processor.py:153} INFO - Started process (PID=1147) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:45.000+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:14:45.001+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:14:45.001+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:45.339+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:14:45.339+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:14:45.340+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:14:45.351+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.358 seconds
[2024-05-30T09:15:15.474+0000] {processor.py:153} INFO - Started process (PID=1158) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:15.477+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:15:15.479+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:15:15.479+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:15.843+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:15:15.842+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:15:15.844+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:15.858+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.388 seconds
[2024-05-30T09:15:46.688+0000] {processor.py:153} INFO - Started process (PID=1169) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:46.690+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:15:46.691+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:15:46.691+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:47.032+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:15:47.031+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:15:47.032+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:15:47.045+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.363 seconds
[2024-05-30T09:16:17.126+0000] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:17.130+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:16:17.131+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:16:17.131+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:17.459+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:16:17.458+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:16:17.459+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:17.469+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.350 seconds
[2024-05-30T09:16:48.377+0000] {processor.py:153} INFO - Started process (PID=1191) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:48.379+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:16:48.380+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:16:48.380+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:48.778+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:16:48.777+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:16:48.778+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:16:48.791+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.422 seconds
[2024-05-30T09:17:19.662+0000] {processor.py:153} INFO - Started process (PID=1202) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:19.663+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:17:19.665+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:17:19.665+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:19.967+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:17:19.966+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:17:19.967+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:19.977+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.323 seconds
[2024-05-30T09:17:50.081+0000] {processor.py:153} INFO - Started process (PID=1213) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:50.083+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:17:50.084+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:17:50.084+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:50.408+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:17:50.407+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:17:50.409+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:17:50.419+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.343 seconds
[2024-05-30T09:18:21.353+0000] {processor.py:153} INFO - Started process (PID=1224) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:21.356+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:18:21.358+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:18:21.357+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:21.739+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:18:21.738+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:18:21.740+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:21.753+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.408 seconds
[2024-05-30T09:18:51.796+0000] {processor.py:153} INFO - Started process (PID=1235) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:51.797+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:18:51.798+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:18:51.798+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:52.140+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:18:52.139+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:18:52.140+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:18:52.157+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.365 seconds
[2024-05-30T09:19:23.044+0000] {processor.py:153} INFO - Started process (PID=1246) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:23.047+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:19:23.049+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:19:23.048+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:23.379+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:19:23.378+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:19:23.379+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:23.393+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.360 seconds
[2024-05-30T09:19:53.470+0000] {processor.py:153} INFO - Started process (PID=1257) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:53.473+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:19:53.475+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:19:53.474+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:53.791+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:19:53.789+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:19:53.791+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:19:53.804+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.340 seconds
[2024-05-30T09:20:23.857+0000] {processor.py:153} INFO - Started process (PID=1268) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:23.858+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:20:23.859+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:20:23.859+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:24.208+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:20:24.207+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:20:24.209+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:24.222+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.370 seconds
[2024-05-30T09:20:55.066+0000] {processor.py:153} INFO - Started process (PID=1279) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:55.068+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:20:55.068+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:20:55.068+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:55.440+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:20:55.439+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:20:55.440+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:20:55.475+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.414 seconds
[2024-05-30T09:21:26.406+0000] {processor.py:153} INFO - Started process (PID=1290) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:26.409+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:21:26.410+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:21:26.410+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:26.703+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:21:26.702+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:21:26.703+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:26.714+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.317 seconds
[2024-05-30T09:21:56.800+0000] {processor.py:153} INFO - Started process (PID=1301) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:56.802+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:21:56.802+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:21:56.802+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:57.129+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:21:57.129+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:21:57.130+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:21:57.142+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.347 seconds
[2024-05-30T09:22:28.042+0000] {processor.py:153} INFO - Started process (PID=1312) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:28.044+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:22:28.045+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:22:28.045+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:28.383+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:22:28.382+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:22:28.383+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:28.396+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.361 seconds
[2024-05-30T09:22:58.501+0000] {processor.py:153} INFO - Started process (PID=1323) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:58.503+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:22:58.504+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:22:58.504+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:58.885+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:22:58.883+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:22:58.885+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:22:58.924+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.431 seconds
[2024-05-30T09:23:29.775+0000] {processor.py:153} INFO - Started process (PID=1334) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:23:29.777+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:23:29.778+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:23:29.778+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:23:30.133+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:23:30.132+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:23:30.134+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:23:30.145+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.383 seconds
[2024-05-30T09:24:01.072+0000] {processor.py:153} INFO - Started process (PID=1345) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:01.075+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:24:01.076+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:24:01.076+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:01.430+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:24:01.429+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:24:01.430+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:01.441+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.376 seconds
[2024-05-30T09:24:32.408+0000] {processor.py:153} INFO - Started process (PID=1356) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:32.410+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:24:32.411+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:24:32.411+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:32.732+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:24:32.731+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:24:32.732+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:24:32.744+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.346 seconds
[2024-05-30T09:25:03.651+0000] {processor.py:153} INFO - Started process (PID=1367) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:03.654+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:25:03.656+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:25:03.656+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:04.035+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:25:04.034+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:25:04.035+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:04.050+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.407 seconds
[2024-05-30T09:25:34.983+0000] {processor.py:153} INFO - Started process (PID=1378) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:34.985+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:25:34.986+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:25:34.986+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:35.303+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:25:35.302+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:25:35.304+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:25:35.314+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.340 seconds
[2024-05-30T09:26:06.300+0000] {processor.py:153} INFO - Started process (PID=1389) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:06.302+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:26:06.303+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:06.303+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:06.705+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:06.704+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:26:06.705+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:06.719+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.427 seconds
[2024-05-30T09:26:37.641+0000] {processor.py:153} INFO - Started process (PID=1400) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:37.643+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:26:37.644+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:37.644+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:38.011+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:38.010+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:26:38.011+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:38.023+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.390 seconds
[2024-05-30T09:26:47.780+0000] {processor.py:153} INFO - Started process (PID=1411) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:47.782+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:26:47.783+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:47.782+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:48.151+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:26:48.150+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:26:48.151+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:26:48.165+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.393 seconds
[2024-05-30T09:27:18.275+0000] {processor.py:153} INFO - Started process (PID=1422) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:18.277+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:27:18.278+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:27:18.278+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:18.613+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:27:18.612+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:27:18.613+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:18.629+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.362 seconds
[2024-05-30T09:27:49.499+0000] {processor.py:153} INFO - Started process (PID=1433) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:49.501+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:27:49.502+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:27:49.502+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:49.833+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:27:49.832+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:27:49.833+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:27:49.845+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.352 seconds
[2024-05-30T09:28:31.082+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:28:31.084+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:28:31.087+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:28:31.086+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:28:32.215+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:28:32.211+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:28:32.215+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:28:32.243+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.169 seconds
[2024-05-30T09:29:02.353+0000] {processor.py:153} INFO - Started process (PID=202) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:02.356+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:29:02.357+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:29:02.357+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:02.661+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:29:02.660+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/etl_from_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_from_csv.py", line 12, in <module>
    schedule='0 8 * * *'
TypeError: __init__() got an unexpected keyword argument 'schedule'
[2024-05-30T09:29:02.661+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:02.674+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.333 seconds
[2024-05-30T09:29:11.579+0000] {processor.py:153} INFO - Started process (PID=213) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:11.582+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:29:11.583+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:29:11.583+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:11.961+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:11.973+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.404 seconds
[2024-05-30T09:29:40.042+0000] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:40.044+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:29:40.045+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:29:40.045+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:40.453+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:29:40.487+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.456 seconds
[2024-05-30T09:30:11.340+0000] {processor.py:153} INFO - Started process (PID=235) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:11.344+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:30:11.347+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:30:11.347+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:11.775+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:11.786+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.465 seconds
[2024-05-30T09:30:42.698+0000] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:42.700+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:30:42.701+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:30:42.701+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:43.085+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:30:43.097+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.406 seconds
[2024-05-30T09:31:13.281+0000] {processor.py:153} INFO - Started process (PID=257) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:13.283+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:31:13.284+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:31:13.284+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:13.640+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:13.671+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.396 seconds
[2024-05-30T09:31:44.553+0000] {processor.py:153} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:44.556+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:31:44.557+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:31:44.557+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:44.908+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:31:44.918+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.374 seconds
[2024-05-30T09:32:15.015+0000] {processor.py:153} INFO - Started process (PID=279) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:15.020+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:32:15.021+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:32:15.021+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:15.387+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:15.397+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.398 seconds
[2024-05-30T09:32:46.245+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:46.246+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:32:46.246+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:32:46.246+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:46.594+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:32:46.621+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.380 seconds
[2024-05-30T09:33:17.589+0000] {processor.py:153} INFO - Started process (PID=301) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:17.591+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:33:17.592+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:33:17.592+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:17.981+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:18.001+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.418 seconds
[2024-05-30T09:33:48.953+0000] {processor.py:153} INFO - Started process (PID=312) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:48.955+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:33:48.956+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:33:48.956+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:49.345+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:33:49.355+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.410 seconds
[2024-05-30T09:34:20.261+0000] {processor.py:153} INFO - Started process (PID=323) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:20.264+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:34:20.265+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:34:20.265+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:20.617+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:20.631+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.377 seconds
[2024-05-30T09:34:51.683+0000] {processor.py:153} INFO - Started process (PID=334) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:51.685+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:34:51.687+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:34:51.687+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:52.062+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:34:52.100+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.427 seconds
[2024-05-30T09:35:22.891+0000] {processor.py:153} INFO - Started process (PID=345) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:22.893+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:35:22.894+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:35:22.894+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:23.272+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:23.281+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.398 seconds
[2024-05-30T09:35:54.210+0000] {processor.py:153} INFO - Started process (PID=356) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:54.212+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:35:54.213+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:35:54.213+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:54.677+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:35:54.689+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.487 seconds
[2024-05-30T09:36:25.491+0000] {processor.py:153} INFO - Started process (PID=367) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:25.493+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:36:25.495+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:36:25.495+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:25.900+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:25.914+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.431 seconds
[2024-05-30T09:36:56.780+0000] {processor.py:153} INFO - Started process (PID=378) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:56.783+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:36:56.784+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:36:56.784+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:57.105+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:36:57.118+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.345 seconds
[2024-05-30T09:37:28.064+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:28.067+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:37:28.068+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:37:28.068+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:28.521+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:28.529+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.473 seconds
[2024-05-30T09:37:59.399+0000] {processor.py:153} INFO - Started process (PID=400) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:59.400+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:37:59.401+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:37:59.401+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:59.743+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:37:59.755+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.362 seconds
[2024-05-30T09:38:30.708+0000] {processor.py:153} INFO - Started process (PID=411) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:38:30.710+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:38:30.711+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:38:30.711+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:38:31.049+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:38:31.058+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.356 seconds
[2024-05-30T09:40:21.022+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:21.022+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:40:21.023+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:40:21.023+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:21.289+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:21.296+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.276 seconds
[2024-05-30T09:40:51.325+0000] {processor.py:153} INFO - Started process (PID=297) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:51.325+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:40:51.325+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:40:51.325+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:51.606+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:40:51.615+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.292 seconds
[2024-05-30T09:41:21.709+0000] {processor.py:153} INFO - Started process (PID=308) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:21.709+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:41:21.710+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:41:21.709+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:22.692+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:22.704+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.997 seconds
[2024-05-30T09:41:52.903+0000] {processor.py:153} INFO - Started process (PID=319) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:52.905+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:41:52.906+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:41:52.906+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:53.372+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:41:53.380+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.481 seconds
[2024-05-30T09:42:35.997+0000] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:42:35.998+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:42:35.998+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:42:35.998+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:42:36.387+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:42:36.394+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.399 seconds
[2024-05-30T09:43:06.630+0000] {processor.py:153} INFO - Started process (PID=196) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:06.634+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:43:06.643+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:43:06.642+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:15.527+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:17.125+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 10.550 seconds
[2024-05-30T09:43:47.564+0000] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:47.567+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:43:47.568+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:43:47.567+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:56.092+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:43:56.151+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 8.596 seconds
[2024-05-30T09:44:26.618+0000] {processor.py:153} INFO - Started process (PID=222) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:44:26.624+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:44:26.629+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:44:26.629+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:44:35.814+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:44:35.834+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 9.266 seconds
[2024-05-30T09:45:06.758+0000] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:06.769+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:45:06.775+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:45:06.775+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:08.564+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:08.584+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.847 seconds
[2024-05-30T09:45:39.224+0000] {processor.py:153} INFO - Started process (PID=244) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:39.229+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:45:39.238+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:45:39.237+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:46.351+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:45:46.456+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 7.284 seconds
[2024-05-30T09:46:17.244+0000] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:46:17.245+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:46:17.246+0000] {logging_mixin.py:115} INFO - [2024-05-30T09:46:17.246+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:46:21.047+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:46:21.089+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 3.848 seconds
[2024-05-30T09:49:50.134+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:49:50.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:49:50.138+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:49:50.138+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:49:51.320+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:49:51.406+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:49:51.405+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:49:51.503+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:49:51.503+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:49:51.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.395 seconds
[2024-05-30T09:50:22.173+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:22.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:50:22.175+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:50:22.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:22.882+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:23.415+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:50:23.412+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:50:23.454+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:50:23.454+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:50:23.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.304 seconds
[2024-05-30T09:50:54.373+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:54.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:50:54.404+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:50:54.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:58.791+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:50:59.939+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:50:59.892+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:51:00.314+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:51:00.309+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:51:00.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 6.300 seconds
[2024-05-30T09:51:31.205+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:51:31.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:51:31.223+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:51:31.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:51:32.259+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:51:32.552+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:51:32.551+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:51:32.567+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:51:32.567+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:51:32.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.411 seconds
[2024-05-30T09:52:02.994+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:02.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:52:02.999+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:02.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:03.476+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:03.514+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:03.513+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:52:03.532+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:03.532+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:52:03.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.566 seconds
[2024-05-30T09:52:33.888+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:33.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:52:33.889+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:33.889+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:34.219+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:52:34.389+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:34.389+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:52:34.411+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:52:34.410+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:52:34.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.540 seconds
[2024-05-30T09:53:04.711+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:04.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:53:04.712+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:04.712+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:04.935+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:04.963+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:04.962+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:53:04.986+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:04.986+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:53:04.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.289 seconds
[2024-05-30T09:53:35.372+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:35.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:53:35.374+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:35.374+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:35.563+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:53:35.635+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:35.635+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:53:35.651+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:53:35.651+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:53:35.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.301 seconds
[2024-05-30T09:54:05.959+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:05.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:54:05.961+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:05.961+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:06.174+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:06.196+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:06.195+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:54:06.210+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:06.210+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:54:06.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.264 seconds
[2024-05-30T09:54:36.634+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:36.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:54:36.637+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:36.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:36.863+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:54:36.956+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:36.956+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:54:36.966+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:54:36.966+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:54:36.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.344 seconds
[2024-05-30T09:55:07.370+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:07.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:55:07.377+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:07.376+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:07.597+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:07.622+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:07.621+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:55:07.639+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:07.639+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:55:07.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.295 seconds
[2024-05-30T09:55:38.103+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:38.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:55:38.108+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:38.107+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:38.434+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:55:38.816+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:38.816+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:55:38.826+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:55:38.826+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:55:38.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.738 seconds
[2024-05-30T09:56:09.193+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:09.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:56:09.196+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:09.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:09.484+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:09.524+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:09.524+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:56:09.542+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:09.542+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:56:09.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.497 seconds
[2024-05-30T09:56:40.133+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:40.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:56:40.135+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:40.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:40.397+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:56:40.473+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:40.473+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:56:40.490+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:56:40.489+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:56:40.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.383 seconds
[2024-05-30T09:57:10.915+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:10.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:57:10.916+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:10.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:11.199+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:11.223+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:11.223+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:57:11.239+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:11.239+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:57:11.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.352 seconds
[2024-05-30T09:57:41.674+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:41.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:57:41.677+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:41.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:41.909+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:57:42.009+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:42.009+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:57:42.020+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:57:42.020+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:57:42.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.364 seconds
[2024-05-30T09:58:12.471+0000] {processor.py:161} INFO - Started process (PID=467) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:12.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:58:12.476+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:12.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:12.716+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:12.757+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:12.756+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:58:12.776+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:12.776+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:58:12.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.330 seconds
[2024-05-30T09:58:43.297+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:43.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:58:43.306+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:43.305+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:43.545+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:58:43.648+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:43.648+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:58:43.660+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:58:43.659+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:58:43.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.388 seconds
[2024-05-30T09:59:14.131+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:14.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:59:14.136+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:14.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:14.397+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:14.433+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:14.433+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:59:14.463+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:14.463+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:59:14.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.355 seconds
[2024-05-30T09:59:44.981+0000] {processor.py:161} INFO - Started process (PID=518) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:44.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T09:59:44.983+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:44.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:45.218+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T09:59:45.457+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:45.456+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T09:59:45.472+0000] {logging_mixin.py:188} INFO - [2024-05-30T09:59:45.471+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-11 08:00:00+00:00, run_after=2024-03-12 08:00:00+00:00
[2024-05-30T09:59:45.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.516 seconds
[2024-05-30T10:00:16.074+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:16.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:00:16.091+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:00:16.089+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:20.606+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:20.934+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:00:20.933+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:00:21.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 5.076 seconds
[2024-05-30T10:00:51.364+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:51.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:00:51.374+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:00:51.372+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:52.221+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:00:52.661+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:00:52.660+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:00:52.709+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:00:52.709+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-03-28 08:00:00+00:00, run_after=2024-03-29 08:00:00+00:00
[2024-05-30T10:00:52.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.389 seconds
[2024-05-30T10:01:23.588+0000] {processor.py:161} INFO - Started process (PID=933) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:01:23.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:01:23.594+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:01:23.593+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:01:25.880+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:01:26.099+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:01:26.092+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:01:26.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 2.605 seconds
[2024-05-30T10:01:57.677+0000] {processor.py:161} INFO - Started process (PID=1240) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:01:57.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:01:57.686+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:01:57.684+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:02:01.804+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:02:05.825+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:02:05.821+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:02:06.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 8.847 seconds
[2024-05-30T10:02:37.182+0000] {processor.py:161} INFO - Started process (PID=1373) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:02:37.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:02:37.188+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:02:37.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:02:38.269+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:02:38.384+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:02:38.382+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:02:38.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.334 seconds
[2024-05-30T10:03:09.449+0000] {processor.py:161} INFO - Started process (PID=1390) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:03:09.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:03:09.454+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:03:09.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:03:09.923+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:03:10.148+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:03:10.146+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:03:10.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.761 seconds
[2024-05-30T10:36:20.950+0000] {processor.py:161} INFO - Started process (PID=1409) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:36:20.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T10:36:20.952+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:36:20.951+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:36:21.915+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T10:36:22.004+0000] {logging_mixin.py:188} INFO - [2024-05-30T10:36:22.000+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T10:36:22.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.151 seconds
[2024-05-30T11:23:53.924+0000] {processor.py:161} INFO - Started process (PID=1428) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T11:23:53.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T11:23:53.928+0000] {logging_mixin.py:188} INFO - [2024-05-30T11:23:53.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T11:23:54.734+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T11:23:55.012+0000] {logging_mixin.py:188} INFO - [2024-05-30T11:23:55.012+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T11:23:55.026+0000] {logging_mixin.py:188} INFO - [2024-05-30T11:23:55.026+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T11:23:55.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.130 seconds
[2024-05-30T12:27:50.282+0000] {processor.py:161} INFO - Started process (PID=1449) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T12:27:50.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T12:27:50.295+0000] {logging_mixin.py:188} INFO - [2024-05-30T12:27:50.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T12:27:51.806+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T12:27:51.893+0000] {logging_mixin.py:188} INFO - [2024-05-30T12:27:51.892+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T12:27:51.932+0000] {logging_mixin.py:188} INFO - [2024-05-30T12:27:51.932+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T12:27:51.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.696 seconds
[2024-05-30T13:50:19.380+0000] {processor.py:161} INFO - Started process (PID=1466) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T13:50:19.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T13:50:19.393+0000] {logging_mixin.py:188} INFO - [2024-05-30T13:50:19.391+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T13:50:19.911+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T13:50:20.156+0000] {logging_mixin.py:188} INFO - [2024-05-30T13:50:20.156+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T13:50:20.195+0000] {logging_mixin.py:188} INFO - [2024-05-30T13:50:20.195+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T13:50:20.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.863 seconds
[2024-05-30T14:54:51.804+0000] {processor.py:161} INFO - Started process (PID=1483) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T14:54:51.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T14:54:51.813+0000] {logging_mixin.py:188} INFO - [2024-05-30T14:54:51.811+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T14:54:52.361+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T14:54:52.418+0000] {logging_mixin.py:188} INFO - [2024-05-30T14:54:52.416+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T14:54:52.453+0000] {logging_mixin.py:188} INFO - [2024-05-30T14:54:52.453+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T14:54:52.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.675 seconds
[2024-05-30T16:03:23.112+0000] {processor.py:161} INFO - Started process (PID=1500) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T16:03:23.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T16:03:23.127+0000] {logging_mixin.py:188} INFO - [2024-05-30T16:03:23.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T16:03:23.686+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T16:03:23.868+0000] {logging_mixin.py:188} INFO - [2024-05-30T16:03:23.867+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T16:03:23.882+0000] {logging_mixin.py:188} INFO - [2024-05-30T16:03:23.882+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T16:03:23.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.800 seconds
[2024-05-30T17:11:01.832+0000] {processor.py:161} INFO - Started process (PID=1519) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T17:11:01.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T17:11:01.841+0000] {logging_mixin.py:188} INFO - [2024-05-30T17:11:01.840+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T17:11:02.425+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T17:11:02.487+0000] {logging_mixin.py:188} INFO - [2024-05-30T17:11:02.485+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T17:11:02.511+0000] {logging_mixin.py:188} INFO - [2024-05-30T17:11:02.511+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T17:11:02.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.717 seconds
[2024-05-30T18:18:12.756+0000] {processor.py:161} INFO - Started process (PID=1537) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T18:18:12.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T18:18:12.767+0000] {logging_mixin.py:188} INFO - [2024-05-30T18:18:12.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T18:18:14.239+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T18:18:14.483+0000] {logging_mixin.py:188} INFO - [2024-05-30T18:18:14.482+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T18:18:14.503+0000] {logging_mixin.py:188} INFO - [2024-05-30T18:18:14.503+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T18:18:14.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.769 seconds
[2024-05-30T19:22:10.437+0000] {processor.py:161} INFO - Started process (PID=1553) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T19:22:10.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T19:22:10.439+0000] {logging_mixin.py:188} INFO - [2024-05-30T19:22:10.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T19:22:11.693+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T19:22:11.768+0000] {logging_mixin.py:188} INFO - [2024-05-30T19:22:11.765+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T19:22:11.804+0000] {logging_mixin.py:188} INFO - [2024-05-30T19:22:11.803+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T19:22:11.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.387 seconds
[2024-05-30T20:46:58.318+0000] {processor.py:161} INFO - Started process (PID=1570) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T20:46:58.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T20:46:58.333+0000] {logging_mixin.py:188} INFO - [2024-05-30T20:46:58.331+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T20:46:58.890+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T20:46:59.122+0000] {logging_mixin.py:188} INFO - [2024-05-30T20:46:59.121+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T20:46:59.142+0000] {logging_mixin.py:188} INFO - [2024-05-30T20:46:59.141+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T20:46:59.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 0.887 seconds
[2024-05-30T21:52:23.636+0000] {processor.py:161} INFO - Started process (PID=1589) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T21:52:23.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T21:52:23.643+0000] {logging_mixin.py:188} INFO - [2024-05-30T21:52:23.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T21:52:24.551+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T21:52:24.658+0000] {logging_mixin.py:188} INFO - [2024-05-30T21:52:24.648+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T21:52:24.708+0000] {logging_mixin.py:188} INFO - [2024-05-30T21:52:24.707+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T21:52:24.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.098 seconds
[2024-05-30T22:56:46.066+0000] {processor.py:161} INFO - Started process (PID=1607) to work on /opt/airflow/dags/etl_from_csv.py
[2024-05-30T22:56:46.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_from_csv.py for tasks to queue
[2024-05-30T22:56:46.069+0000] {logging_mixin.py:188} INFO - [2024-05-30T22:56:46.068+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T22:56:46.597+0000] {processor.py:840} INFO - DAG(s) 'etl_csv_files' retrieved from /opt/airflow/dags/etl_from_csv.py
[2024-05-30T22:56:47.167+0000] {logging_mixin.py:188} INFO - [2024-05-30T22:56:47.165+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-30T22:56:47.202+0000] {logging_mixin.py:188} INFO - [2024-05-30T22:56:47.201+0000] {dag.py:3834} INFO - Setting next_dagrun for etl_csv_files to 2024-04-26 08:00:00+00:00, run_after=2024-04-27 08:00:00+00:00
[2024-05-30T22:56:47.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_from_csv.py took 1.178 seconds
